import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Not Primitive</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/logo.png" />
			</Head>

			<main className=" grid h-screen place-items-center bg-black">
				<h1 className="font-display text-4xl text-white">Coming Soon.</h1>
			</main>
		</>
	);
};

export default Home;
