import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Chat } from '@/components/chat';

import localFont from 'next/font/local';
import '../styles/globals.css';

const inter = localFont({ src: '../fonts/Inter.var.woff2' });

export const metadata = {
	title: 'Millennium Paving Stones',
	description: 'Generated by Next.js',
	icons: {
		icon: './favicon.ico'
	}
};

export default function RootLayout({ children }: React.PropsWithChildren) {
	return (
		<html lang="en" className={`${inter.className} text-gray-900`}>
			<body>
				<Header />
				{children}
				<Footer />

				<Chat />
			</body>
		</html>
	);
}
