import { Header } from '@/components/header';
import '../styles/globals.css';
import { Footer } from '@/components/footer';

export const metadata = {
	title: 'Millennium Paving Stones',
	description: 'Generated by Next.js'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
